### ISSUE TITLE
Parser throwing UnicodeDecodeError on UA with Chinese characters

### ISSUE THREAD

**Issue by cfpatrick** [ua-parser/uap-python#38] opened 2015-12-21 02:44 UTC
Here is the User Agent header in question:

    Mozilla/5.0 (Linux; U; Android 4.4.3; zh-cn; 蝶变9999 Build/KOT49H) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025469 Mobile Safari/533.1 MicroMessenger/6.2.2.54_rec1912d.581 NetType/3gnet Language/zh_CN

And here is the traceback:

    File "/usr/lib/python2.7/site-packages/user_agents-1.0.1-py2.7.egg/user_agents/parsers.py", line 232, in parse
    return UserAgent(user_agent_string)
    File "/usr/lib/python2.7/site-packages/user_agents-1.0.1-py2.7.egg/user_agents/parsers.py", line 126, in __init__
    ua_dict = user_agent_parser.Parse(user_agent_string)
    File "/usr/lib/python2.7/site-packages/ua_parser/user_agent_parser.py", line 232, in Parse
    'device': ParseDevice(user_agent_string, **jsParseBits),
    File "/usr/lib/python2.7/site-packages/ua_parser/user_agent_parser.py", line 315, in ParseDevice
    device, brand, model = deviceParser.Parse(user_agent_string)
    File "/usr/lib/python2.7/site-packages/ua_parser/user_agent_parser.py", line 203, in Parse
    model = self.MultiReplace(self.model_replacement, match)
    File "/usr/lib/python2.7/site-packages/ua_parser/user_agent_parser.py", line 184, in MultiReplace
    _string = re.sub(r'\$(\d)', _repl, string)
    File "/usr/lib64/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by mattrobenolt** [comment] 2016-01-02 22:07
I'll look into this and see. It should be a trivial fix.

**Comment by mattrobenolt** [comment] 2016-01-03 20:09
Hmm, @cfpatrick what version of uap-python is this with?

Testing against latest (0.6.1), I can't reproduce:

```python
>>> user_agent_parser.Parse(u'Mozilla/5.0 (Linux; U; Android 4.4.3; zh-cn; 蝶变9999 Build/KOT49H) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025469 Mobile Safari/533.1 MicroMessenger/6.2.2.54_rec1912d.581 NetType/3gnet Language/zh_CN')
{'device': {'brand': 'Generic_Android', 'model': u'\u8776\u53d89999', 'family': u'\u8776\u53d89999'}, 'os': {'major': u'4', 'patch_minor': None, 'minor': u'4', 'family': u'Android', 'patch': u'3'}, 'user_agent': {'major': u'5', 'minor': u'4', 'family': 'QQ Browser Mobile', 'patch': None}, 'string': u'Mozilla/5.0 (Linux; U; Android 4.4.3; zh-cn; \u8776\u53d89999 Build/KOT49H) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025469 Mobile Safari/533.1 MicroMessenger/6.2.2.54_rec1912d.581 NetType/3gnet Language/zh_CN'}
```

**Comment by mattrobenolt** [comment] 2016-01-17 16:01
Closing since I can't reproduce with latest version.

**Closed by mattrobenolt** 2016-01-17 16:01 UTC
