### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by dcramer** [ua-parser/uap-python#9] opened 2015-08-06 17:48 UTC
Apologies for the non-issue issue.

We use ua-parser heavily in Sentry and I'm curious about the status of 0.4.0.

Right now we're at a point where we either will be forking the old ua-parser (and possibly vendoring it), or helping push this through.

Mostly the reason for this is we need to get updated support for things like Microsoft Edge.

**Comment by elsigh** [comment] 2015-08-06 18:23
So I'm clear, are you saying the issue is that the current parser is using an old version of regexes.yaml?
Ideally, uap-python should just be using the regexes.yaml file from HEAD, and if that ever is broken it should be fixed.
This is one of those trade-offs we made when splitting up uap-core from the language implementations, and I'm totally open to ideas to solve that problem - because I agree that sucks.
One idea I had recently was to switch from a pinned submodule to the git subtree approach. Thoughts?

**Comment by elsigh** [comment] 2015-08-06 18:24
Also, do you know if the current regexes.yaml is somehow incompatible with the current version of `uap-python`? I'm not using `uap-python` these days so I just don't know.

**Comment by elsigh** [comment] 2015-08-06 18:24
See Issue #6

**Comment by dcramer** [comment] 2015-08-06 18:24
I dont know much about git subtrees, but mostly I'm asking "is a new release coming soon?" 

I can look into pulling down the latest regexes. I'm not familiar with the inner workings so wasn't aware of that option. I assume that's something I can do without vendoring? i.e. I could specify it at runtime?

**Comment by elsigh** [comment] 2015-08-06 18:29
I don't know what you mean by "vendoring".

Ideally, `uap-python` and `uap-core` don't have "releases" and you can just use HEAD. I think you're just saying the same thing as #6 

Can you try replacing `uap-core` with the latest version and see if it works? It's only regexes.yaml that matters from `uap-core`

**Comment by dcramer** [comment] 2015-08-06 18:38
@elsigh so we release a giant Python package which specifies lots of dependencies (which come from external sources). We can't simply use HEAD (or anything related to Git) in this situation.

Vendoring would be the equivalent of me copying the code into our repository and basically never using the upstream project again. We'd effectively have to maintain all of the code in one way or another, but it comes w/ the downside that we constantly have to update things instead of just relying on updating a dependency.

**Comment by elsigh** [comment] 2015-08-06 18:41
If #6 was solved would you be good to go?

**Comment by dcramer** [comment] 2015-08-06 18:42
It would help, but its also #5 -- actually pushing out a new release

I think being able to just update the regexes is super valuable, so ideally taht could be something that libraries allow at runtime

i.e. ua_parser.set_regex(...)

**Comment by elsigh** [comment] 2015-08-06 18:46
I think you can just point to commit hashes on master. I'm going to mark #5 as will not fix.

**Comment by dcramer** [comment] 2015-08-06 18:47
No you cannot point to commit hashes. That is not a thing in the Python world.

**Comment by elsigh** [comment] 2015-08-06 18:51
Sure it is - you have a build step that does a git clone using a commit hash.. But I don't know enough about your build system - do you rely on pip releases at the moment? Otherwise what's a release?

I think pip is cool, but I don't know that anyone is currently dedicated to pushing pip releases. In the past that was done by @commenthol but while I like pip I actually don't like the dependency and in my own projects I have build steps which do `git clone` with commit hashes so that things are stable.

**Comment by dcramer** [comment] 2015-08-06 19:31
@elsigh unfortunately you're in the small percent that does things that way. If you cant trust my word (I've been doing Python, open source, and very active for a decade), you can simply look at the install numbers on the Python website. It's important to also note that pip != the python registry (PyPi).

We ship a standard Python app, that app versions dependencies (i.e. ua-parser >= 0.3.6), and it is not possible to ship a dependency that says "look for the version on GitHub). It's not supported by the Python build tools, and people that do this kind of stuff cant simply customize their installation for a minor dependency (ua-parser is one of 120+ third party dependencies we support).

If the python index won't be supported we'll simply fork ua-parser and version it ourselves, as the solutions proposed dont work for the greater python ecosystem.

**Comment by elsigh** [comment] 2015-08-06 19:37
How would you feel about doing the push to pypi and becoming a contributor on `uap-python`?

**Comment by dcramer** [comment] 2015-08-06 19:38
We wouldn't be opposed to helping maintain it, though it sounds like theres some complexities you might want to sort out first.

My personal recommendation for the subtree/etc problem would be just to maintain a single repository, with each SDK being its own subpath. Seems like it'd be a lot easier, and then you could coordinate releases of all versions at the same time. Though that may make it harder to simply depend on a git SHA (I'm not sure if theres good solutions)

**Comment by elsigh** [comment] 2015-08-06 20:27
What are the complexities we need to sort out?

Your recommendation is actually how the project was previously structured and we finally gave in and created an org with a `uap-core` that each language version embeds. The reality is that this works better for maintenance/issues/coordination. The downside is maintenance of each individual repo.

**Comment by elsigh** [comment] 2015-08-06 22:11
But like I say, I think the project is totally open to someone who's using it in production who wants to coordinate pushing to pypi.

**Comment by dcramer** [comment] 2015-08-06 22:12
@elsigh just commenting on what you mentioned regarding submodules. I am not opposed to anything, but I am in agreement that its a PITA to maintain submodules (we have webhooks for auto commiting to repos that do this in our own projects)

**Comment by elsigh** [comment] 2015-08-06 22:19
It would be really cool if Sentry could be a maintainer of this baby.

The subtree approach looks like:
http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

The downside of linking to master of uap-core is that it's a moving target, but I actually think that's how things should be and that it should be very rare that the regexes.yaml changes such that it causes a parser to break.

**Comment by elsigh** [comment] 2015-08-06 22:27
I actually just did this to the go implementation (which I'm currently using in production).
https://github.com/ua-parser/uap-go/commit/7485c5bea8c5a6a11bb33a0b0daa44dd8a6f683a

**Comment by elsigh** [comment] 2015-08-07 13:29
I'm going to close this as a dupe of #6. @dcramer Please let me know if you would like to push releases to pypi! =)

**Closed by elsigh** 2015-08-07 13:29 UTC

**Comment by elsigh** [comment] 2015-08-11 18:02
@dcramer any thoughts around taking over pushes?
