### ISSUE TITLE
use larger LRU cache for user_agent_parser?

### ISSUE THREAD

**Issue by jogo** [ua-parser/uap-python#55] opened 2017-08-08 23:06 UTC
https://github.com/ua-parser/uap-python/blob/6247d697a97d81eb77b3970f48bac2ad80692593/ua_parser/user_agent_parser.py#L219

Instead of using the built in cache for 20 values, that gets cleared out if it's too big, we are using a lru cache of 1000 values. This has reduced the time it takes for user_agent_parser to run (when tested over 100,000 real user agents) by about 3x, and appears to use less then a MB of ram.

**Comment by mattrobenolt** [comment] 2017-08-08 23:18
If you'd like to submit a PR for a full LRU implementation, that'd be fine to me. If we do that, it'd be nice to have it configurable since I might not want to waste 1MB of RAM or whatever.

**Comment by jogo** [comment] 2017-08-08 23:31
I'll post a PR tomorrow based on https://pypi.python.org/pypi/backports.functools_lru_cache (as recommended by http://python-future.org/imports.html)

**Comment by mattrobenolt** [comment] 2020-02-27 00:15
I am going to close this since I still disagree with this existing within uap-python. If you want better caching or LRU logic, it's trivial to add that into your application. I think this could be expected behavior and a waste of RAM for users who are conscious of this.

**Closed by mattrobenolt** 2020-02-27 00:15 UTC
